### ISSUE TITLE
Problem with deep objects

### ISSUE THREAD

**Issue by frontsideair** [kiliman/remix-typedjson#2]
When I wrap the loader data in another object, it fails while deserializing. Here's a reproduction: https://stackblitz.com/edit/github-gbcwza?file=app%2Froutes%2Ftest.tsx

The code: 
```tsx
  return typedjson(
    { data: { greeting: "hello", today: new Date() } },
  );
```

**Comment by kiliman** [comment]
It actually works as designed. The problem is that you modified the loader return, but not how you used it in the route. It's basically telling you that you should be using
```ts
loaderData.data.today.toLocaleDateString()
```
If you think about it, that's pretty cool!

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/47168/181121343-19913b95-aff5-45f7-ae1f-89221fbb4478.png">

**Comment by frontsideair** [comment]
You're absolutely correct about this case, I botched the repro while trying to shrink it. The following is the correct reproduction and I removed the `<p>` to reduce confusion.

```tsx
  return typedjson(
    { data: [{ greeting: "hello", today: new Date() }] },
  );
```

I also updated the StackBlitz, it should be visible with the same url.

**Comment by kiliman** [comment]
Ugh. You are correct. I copied the loader to the resource route so I could see what the actual payload was.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/47168/181124493-ce5b3d57-4853-4c41-a648-c5dcbf53bc4f.png">

Meta should have been: `{ "data.0.today": "date" }`
https://github-gbcwza-vh4vsh--3000.local.webcontainer.io/resource

**Comment by kiliman** [comment]
This works now in v0.0.7. Thanks for the bug report!

https://stackblitz.com/edit/github-gbcwza-9pxd9e?file=app%2Froutes%2Ftest.tsx
