### ISSUE TITLE
Adding support for `key` in `useTypedFetcher`

### ISSUE THREAD

**Issue by DerJacques** [kiliman/remix-typedjson#35]
Remix recently added the ability to provide a `key` to fetchers:
https://remix.run/docs/en/main/hooks/use-fetcher#key

It would be wonderful if `useTypedFetcher` would expose the same argument.

This library is great, so thank you for all your work on this!

**Comment by kiliman** [comment]
Published in v0.4.0

**Comment by DerJacques** [comment]
Fantastic! Thank you.

**Comment by kiliman** [comment]
Let me know if you have any issues. I needed to make sure it works for both Remix v1 (which doesn't support `key`) and Remix v2.2+ (which added it).

**Comment by DerJacques** [comment]
It works perfectly! Thanks a lot for the super quick response.
