### ISSUE TITLE
Update README: `DataFunctionArgs` is being deprecated

### ISSUE THREAD

**Issue by fernandocanizo** [kiliman/remix-typedjson#38]
Hi, according to [this PR from Remix](https://github.com/remix-run/remix/pull/8089), `DataFunctionArgs` is being deprecated, so where the README says: "Make sure your loader and action use the new declaration format:", the example should look like:

```ts
// Old ways
export const loader: LoaderFunction = async ({request}) => {}
export const action: ActionFunction = async ({request}) => {}
export const loader = async ({request}: DataFunctionArgs) => {}
export const action = async ({request}: DataFunctionArgs) => {}

// New way
export const loader = async ({request}: LoaderFunctionArgs) => {}
export const action = async ({request}: ActionFunctionArgs) => {}
```

Although I don't know if there's also code to be touched before editing the documentation.

**Comment by kiliman** [comment]
Thanks for the heads up!
