### ISSUE TITLE
Typed JSON while submitting data to the server?

### ISSUE THREAD

**Issue by abustany** [kiliman/remix-typedjson#40]
`useTypedFetcher` allows getting correctly typed data from the server to the frontend, however it does not seem to be helping when calling `fetcher.submit` with an object as the target? It feels like we could use the current encoding for "complex" values not only for receiving data, but also for sending data to the server?

**Comment by abustany** [comment]
Aha, looks like I can simply use the `serialize` and `deserialize` methods, like this:

```typescript
export async function action({request}: ActionFunctionArgs) {
  const data = deserialize(await request.json());
}

export default Component() {
  const fetcher = useFetcher();
  fetcher.submit(serialize(myObject), {encType: "application/json"});
}
```

**Comment by kiliman** [comment]
I was just going to comment on that. Glad you figured it out.
