### ISSUE TITLE
Add option to serialize custom data types

### ISSUE THREAD

**Issue by IgnisDa** [kiliman/remix-typedjson#5]
Awesome project! 

I would like to serialize `DateTime` (from luxon), inbuilt `URL` data type etc. For reference, I am using https://github.com/clentfort/urql-custom-scalars-exchange to serialize the data in `loader`.

**Comment by kiliman** [comment]
Part of the reason for this package is that I wanted it to be lightweight. If you need more advanced type configuration, I recommend sticking with superjson.

I have a project showing how to use superjson with Remix.
https://github.com/kiliman/remix-superjson

**Comment by IgnisDa** [comment]
Alright makes sense. Thanks for the prompt response!
